/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Khanh Trinh
 */

package edu.nuce.edu.lthdm.springtodolist;

import org.springframework.web.bind.annotation.RestController;
import org.springframework.web.bind.annotation.RequestMapping;
import java.util.List;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestParam;

@RestController
@RequestMapping("/task")
public class TaskController {

    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private TaskRepository taskRepository;

    @GetMapping(path = "/all")
    public List<Task> list() {
        return taskRepository.findAll();
    }

    @GetMapping("/{id}")
    public Task get(@PathVariable Long id) {
        return taskRepository.getOne(id);
    }

    @PutMapping("/{id}")
    public ResponseEntity<?> put(@PathVariable String id,
            @RequestBody Task input) {
        taskRepository.save(input);
        return new ResponseEntity<>(null,
                HttpStatus.valueOf(303));
    }

    @PostMapping
    public ResponseEntity<?> post(@RequestBody Task input) {
        taskRepository.save(input);
        return new ResponseEntity<>(null,
                HttpStatus.valueOf(201));
    }

    @DeleteMapping("/{id}")
    public ResponseEntity<?> delete(@PathVariable Long id) {
        taskRepository.deleteById(id);
        return new ResponseEntity<>(null,
                HttpStatus.valueOf(204));
    }
}
